// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// WatherGetterer is an autogenerated mock type for the WatherGetterer type
type WatherGetterer struct {
	mock.Mock
}

// GetData provides a mock function with given fields: s
func (_m *WatherGetterer) GetData(s string) (*http.Response, error) {
	ret := _m.Called(s)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Response, error)); ok {
		return rf(s)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Response); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWather provides a mock function with given fields: sity
func (_m *WatherGetterer) GetWather(sity string) string {
	ret := _m.Called(sity)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(sity)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewWatherGetterer interface {
	mock.TestingT
	Cleanup(func())
}

// NewWatherGetterer creates a new instance of WatherGetterer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWatherGetterer(t mockConstructorTestingTNewWatherGetterer) *WatherGetterer {
	mock := &WatherGetterer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
