// Code generated by MockGen. DO NOT EDIT.
// Source: main.go

// Package mock_main is a generated GoMock package.
package mock_main

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	github "github.com/google/go-github/v53/github"
	model "studentgit.kata.academy/Alkolex/go-kata/course2/practice/task2/model"
)

// MockGithuber is a mock of Githuber interface.
type MockGithuber struct {
	ctrl     *gomock.Controller
	recorder *MockGithuberMockRecorder
}

// MockGithuberMockRecorder is the mock recorder for MockGithuber.
type MockGithuberMockRecorder struct {
	mock *MockGithuber
}

// NewMockGithuber creates a new mock instance.
func NewMockGithuber(ctrl *gomock.Controller) *MockGithuber {
	mock := &MockGithuber{ctrl: ctrl}
	mock.recorder = &MockGithuberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithuber) EXPECT() *MockGithuberMockRecorder {
	return m.recorder
}

// GetGists mocks base method.
func (m *MockGithuber) GetGists(ctx context.Context, username string) ([]model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGists", ctx, username)
	ret0, _ := ret[0].([]model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGists indicates an expected call of GetGists.
func (mr *MockGithuberMockRecorder) GetGists(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGists", reflect.TypeOf((*MockGithuber)(nil).GetGists), ctx, username)
}

// GetRepos mocks base method.
func (m *MockGithuber) GetRepos(ctx context.Context, username string) ([]model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepos", ctx, username)
	ret0, _ := ret[0].([]model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepos indicates an expected call of GetRepos.
func (mr *MockGithuberMockRecorder) GetRepos(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepos", reflect.TypeOf((*MockGithuber)(nil).GetRepos), ctx, username)
}

// GetGisList mocks base method.
func (m *MockGithuber) GetGisList(arg0 context.Context, arg1 string, arg2 *github.GistListOptions) ([]*github.Gist, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGisList", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*github.Gist)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetGisList indicates an expected call of GetGisList.
func (mr *MockGithuberMockRecorder) GetGisList(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGisList", reflect.TypeOf((*MockGithuber)(nil).GetGisList), arg0, arg1, arg2)
}

// GetRepList mocks base method.
func (m *MockGithuber) GetRepList(arg0 context.Context, arg1 string, arg2 *github.RepositoryListOptions) ([]*github.Gist, *github.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepList", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*github.Gist)
	ret1, _ := ret[1].(*github.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRepList indicates an expected call of GetRepList.
func (mr *MockGithuberMockRecorder) GetRepList(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepList", reflect.TypeOf((*MockGithuber)(nil).GetRepList), arg0, arg1, arg2)
}
