version: "3.9"
services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    environment:
      - TZ=Europe/Moscow
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /portainer/portainer_data:/data
    ports:
      - 8000:8000
      - 9443:9443
    restart: always