// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"
	mock "github.com/stretchr/testify/mock"
	"studentgit.kata.academy/Alkolex/go-kata/course2/3.patterns/3.patterns_strategy/task2.3.3.1/models"
)

// GeneralGithubLister is an autogenerated mock type for the GeneralGithubLister type
type GeneralGithubLister struct {
	mock.Mock
}

// GetItems provides a mock function with given fields: ctx, username, strategy
func (_m *GeneralGithubLister) GetItems(ctx context.Context, username string, strategy GithubLister) ([]models.Item, error) {
	ret := _m.Called(ctx, username, strategy)

	var r0 []models.Item
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, GithubLister) ([]models.Item, error)); ok {
		return rf(ctx, username, strategy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, GithubLister) []models.Item); ok {
		r0 = rf(ctx, username, strategy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Item)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, GithubLister) error); ok {
		r1 = rf(ctx, username, strategy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewGeneralGithubLister interface {
	mock.TestingT
	Cleanup(func())
}

// NewGeneralGithubLister creates a new instance of GeneralGithubLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGeneralGithubLister(t mockConstructorTestingTNewGeneralGithubLister) *GeneralGithubLister {
	mock := &GeneralGithubLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
